### ISSUE TITLE
Compile error for release versions

### ISSUE THREAD

**Issue by rycstar** [cgreen-devs/cgreen#240] opened 2020-09-02 09:04 UTC
As there is no .git directory in the release package, the following error will be reported while doing make.
`
fatal: Not a git repository (or any of the parent directories): .git
src/CMakeFiles/cgreen_shared.dir/build.make:61: recipe for target '../gitrevision.h' failed
make[3]: *** [../gitrevision.h] Error 128
CMakeFiles/Makefile2:1117: recipe for target 'src/CMakeFiles/cgreen_shared.dir/all' failed
make[2]: *** [src/CMakeFiles/cgreen_shared.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make[1]: *** [all] Error 2
Makefile:17: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by thoni56** [comment] 2020-09-02 10:11
Duplicate of #234, I think. You can find a fix in that issue.

**Closed by thoni56** 2020-09-02 10:11 UTC
