### ISSUE TITLE
Add a mechanism for launching test cases in-process

### ISSUE THREAD

**Issue by d-meiser** [cgreen-devs/cgreen#5] opened 2015-09-02 00:00 UTC
In some situations it is desirable to have the test cases run without forking (valgrind, gcov, gdb, etc.). It would be nice to have a mechanism, perhaps via environment variables, to toggle in-process execution of tests.

The following thread on the mailing list has some background info on the issue:

http://sourceforge.net/p/cgreen/mailman/cgreen-devel/thread/CANvsC2voB3-GpT%2BQ05fEXdjJJee5sQF2fzGN1ByTd0OsswinpA@mail.gmail.com/

**Comment by matthargett** [comment] 2015-09-02 19:16
I confirmed that I did implement this at a former employer, but wasn't able to contribute it back (their open source policies changed before they went private/ were acquired). I'll reimplement this and throw up a pull request in the next few days.

**Comment by matthargett** [comment] 2015-09-16 22:03
my colleague @doj is working on getting this and some other changes open sourced. we'll give them a bit before reimplementing it :)

**Comment by doj** [comment] 2015-09-19 08:29
yes, I've made a open source release request. It'll take some days to be reviewed and approved.

**Comment by snieguzary** [comment] 2016-05-18 15:47
Hi guys,
@doj 
Do you have any update on this? Because I also have this functionality implemented, but I don't want to double your work. If you can't share the patches for some reason, please let me know and I will share mine.

Thanks in andvance.
BR, Radoslaw

**Comment by thoni56** [comment] 2016-05-23 10:50
Hi Radoslaw!

No reaction yet from @doj or any other of the possibly involved. I suggest that you prepare a patch and I can add a PR from that to continue the discussion.

**Comment by snieguzary** [comment] 2016-05-23 11:01
@thoni56 
OK, I will share the patch, most likely tomorrow but I can't make any promises as this is a very busy week for me. If you won't get the patch tomorrow, I will share it next week, so please be patient. Thanks!

**Comment by thoni56** [comment] 2016-05-23 11:02
No problem! This issue has been open for a long time already ;-)

**Comment by doj** [comment] 2016-05-23 17:34
Hello Radoslav, decision here are only moving at glacier speed and there's no progress. Go ahead and show us your implementation, it might be better anyway as mine is probably based on a 3 years old version of cgreen.

**Comment by thoni56** [comment] 2016-11-12 10:23
Since #97 allows for this, I'm closing this issue. If there are any aspect that has not been taken care of, please open a more specific issue.

**Closed by thoni56** 2016-11-12 10:23 UTC
Labels: enhancement
